<center> <h1>Introdução ao Pandas</h1> </center>
<center> <h3>Pré-processamento de dados usando Python</h3> </center>

Python tem diversas estruturas para armazenamento de dados. 

Algumas delas são "internas": listas, tuplas, conjuntos, dicionários.

Outras, precisam de bibliotecas específicas: ndarray (Numpy), Series e DataFrames (Pandas).

##### Listas

* mutáveis
* ordenadas
* heterogêneas
* indexada por posição
* delimitada por colchetes [ ]

In [1]:
lista = ['casa', 1.0, 3, [1,2,3]]
lista

['casa', 1.0, 3, [1, 2, 3]]

In [2]:
type(lista)

list

Indexação feita por posição

In [3]:
lista[0]

'casa'

In [4]:
lista[2]

3

In [6]:
lista[-1]

[1, 2, 3]

In [7]:
lista[3]

[1, 2, 3]

In [8]:
lista[-1][0]

1

Um problema sério: operações com listas

In [52]:
a = [1,2.,'3']
a

[1, 2.0, '3']

In [53]:
a*3

[1, 2.0, '3', 1, 2.0, '3', 1, 2.0, '3']

In [54]:
b = []
for i in a:
    b.append(i*3)
b

[3, 6.0, '333']

#### Dicionários

* mutáveis
* não ordenados
* heterogêneos
* indexada por chaves
* delimitada por chaves { }

In [15]:
Dicionario = {"Nome": "Zé", "Idade": 10, "Cidade": "Nazarezinho"}
Dicionario

{'Nome': 'Zé', 'Idade': 10, 'Cidade': 'Nazarezinho'}

In [16]:
type(Dicionario)

dict

Indexação por chaves

In [19]:
Dicionario["Idade"]

10

In [21]:
dic = {'A':{"Abel":33219031, "Antonio": "24563421"}}
dic

{'A': {'Abel': 33219031, 'Antonio': '24563421'}}

In [22]:
dic['A']['Abel']

33219031

#### ndarray - Numpy

A biblioteca Numpy é a biblioteca numérica do Python, e é a base de todas as grandes bibliotecas do ecossistema Python de computação científica e análise de dados, como Scipy, Matplotlib e a própria Pandas. 

A biblioteca Numpy cria uma nova estrutura de dados, chamada de ndarray, que possue algumas similaridades com listas, mas alguns poderes a mais, com destaque para a capacidade de vetorização, que possibilita que qualquer operação feita com a estrutura seja feita elemento a elemento sem a necessidade de um laço para acessar esses elementos, tornando, assim, a operação computacionalmente mais eficiente.

In [37]:
import numpy as np

In [41]:
np.array()

array('a', dtype='<U1')

Existem várias formas de criar arrays, pode ser através do método np.array(): 

1. usando uma lista:

In [46]:
arr = np.array([-2, 4., '7', 9])
arr

array(['-2', '4.0', '7', '9'], dtype='<U32')

String > complex > float > int

In [51]:
1 + 2.0

3.0

2. usando o método arange: `np.arange(inicio, fim, passo)`

In [61]:
arr = np.arange(0, 100, 10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

3. usando o método linspace `np.linspace(inicio, fim, quantidade)`

In [60]:
arr = np.linspace(1, 100, 10)
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

4. outros métodos

In [66]:
arr1 = np.empty(6) # Array vazia com o método empty() normalmente a saída é lixo de memória ou zeros
arr1

array([4.64427697e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [63]:
arr2 = np.eye(4) # eye cria uma array de duas dimensões com 1 na da diagnoal e 0 nos outros elementos
print(arr2, '\n')

arr3 = np.zeros(8) # array contendo 8 'zeros'
print (arr3, '\n')

arr4 = np.ones((4,3)) # array contendo 12 'uns', no formato 4 x 3
print(arr4)

[4.64427697e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[0. 0. 0. 0. 0. 0. 0. 0.] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Vetorização

In [75]:
# vamos criar as arrays A e B para fazer operações com elas

A = np.arange(10)
B = np.arange(2,10)
C = np.array([2, 3, 4, 5, 6, 7, 8, 9, np.nan, np.nan])

print (' A: ', A, '\n', 'B: ', B, '\n', 'C: ', C)

 A:  [0 1 2 3 4 5 6 7 8 9] 
 B:  [2 3 4 5 6 7 8 9] 
 C:  [ 2.  3.  4.  5.  6.  7.  8.  9. nan nan]


In [79]:
A[0]

0

In [70]:
somar = A + B
subtrair = A - B
dividir = A / B
multiplicar = A * B

print('somar: ', somar )
print('subtrair: ', subtrair )
print('dividir: ', dividir )
print('multiplicar: ', multiplicar)

somar:  [10 14 18 22 26 30 34 38 42 46]
subtrair:  [-10 -12 -14 -16 -18 -20 -22 -24 -26 -28]
dividir:  [0.         0.07692308 0.125      0.15789474 0.18181818 0.2
 0.21428571 0.22580645 0.23529412 0.24324324]
multiplicar:  [  0  13  32  57  88 125 168 217 272 333]


Indexação

![Image of Yaktocat](http://www.scipy-lectures.org/_images/numpy_indexing.png)